Repository Bside-Team-Four/popo-client, pull requests merged in 2023-04, with the labels that each got.

#25 [POLL-004] 투표 화면 UI를 개발하라(Full Popup)
  .eslintrc.js
  .pnp.cjs
  .yarn/cache/@emotion-is-prop-valid-npm-0.8.8-261a0f2426-bb7ec6d48c.zip
  .yarn/cache/@emotion-memoize-npm-0.7.4-5648cf11b8-4e3920d4ec.zip
  .yarn/cache/framer-motion-npm-10.10.0-d3a8e57dcb-378301b053.zip
  cypress/e2e/index.cy.ts
  package.json
  public/images/candidate-default.svg
  public/images/category-romance.svg
  public/images/close-icon.svg
  public/images/shuffle_icon.svg
  public/images/skip_icon.svg
  src/app/LayoutProvider.tsx
  src/app/layout.tsx
  src/components/PollPopup/CandidateItem.test.tsx
  src/components/PollPopup/CandidateItem.tsx
  src/components/PollPopup/CandidateList.test.tsx
  src/components/PollPopup/CandidateList.tsx
  src/components/PollPopup/OptionButton.test.tsx
  src/components/PollPopup/OptionButton.tsx
  src/components/PollPopup/OptionButtons.test.tsx
  src/components/PollPopup/OptionButtons.tsx
  src/components/PollPopup/PollHeader.test.tsx
  src/components/PollPopup/PollHeader.tsx
  src/components/PollPopup/Question.test.tsx
  src/components/PollPopup/Question.tsx
  src/components/PollPopup/index.test.tsx
  src/components/PollPopup/index.tsx
  src/components/home/Rabbit.test.tsx
  src/components/home/Timer.test.tsx
  src/components/home/VoteButton.test.tsx
  src/components/home/VoteButton.tsx
  src/components/home/index.test.tsx
  src/components/home/index.tsx
  src/components/popup/FullPopup.test.tsx
  src/components/popup/FullPopup.tsx
  src/components/popup/Portal.test.tsx
  src/components/popup/Portal.tsx
  src/components/provider/SizeThemeProvider.tsx
  src/components/provider/StyledComponentsRegistry.tsx
  src/fixtures/candidate.ts
  src/fixtures/index.ts
  src/fixtures/polls.ts
  src/hooks/useTimerText.test.tsx
  src/hooks/useTimerText.ts
  src/types/Candidate.ts
  src/types/Poll.ts
  src/utils/testHelper.tsx
  yarn.lock
Labels: feature

#27 [POLL-004] react-query setting
  .github/workflows/ci.yml
  .pnp.cjs
  .yarn/cache/@tanstack-match-sorter-utils-npm-8.8.4-488b98c113-d005f50075.zip
  .yarn/cache/@tanstack-query-core-npm-4.27.0-2fd798e498-914b4f01ac.zip
  .yarn/cache/@tanstack-react-query-devtools-npm-4.28.0-44cc5982e5-76d39c4f5d.zip
  .yarn/cache/@tanstack-react-query-npm-4.28.0-4692cd88b9-7baa70d22b.zip
  .yarn/cache/axios-npm-1.3.4-01ea685178-7440edefcf.zip
  .yarn/cache/copy-anything-npm-3.0.3-a24d77ec4d-d456dc5ec9.zip
  .yarn/cache/is-what-npm-4.1.8-57bef8cfbc-b9bec3acff.zip
  .yarn/cache/remove-accents-npm-0.4.2-7cb341092a-84a6988555.zip
  .yarn/cache/superjson-npm-1.12.2-e37d205ed2-cf7735e172.zip
  .yarn/cache/use-sync-external-store-npm-1.2.0-44f75d2564-5c639e0f8d.zip
  package.json
  src/app/LayoutProvider.tsx
  src/components/home/Rabbit.test.tsx
  src/components/home/Timer.test.tsx
  src/components/home/VoteButton.test.tsx
  src/components/home/index.tsx
  src/components/popup/PollPopup/CandidateItem.test.tsx
  src/components/popup/PollPopup/CandidateItem.tsx
  src/components/popup/PollPopup/CandidateList.test.tsx
  src/components/popup/PollPopup/CandidateList.tsx
  src/components/popup/PollPopup/OptionButton.test.tsx
  src/components/popup/PollPopup/OptionButton.tsx
  src/components/popup/PollPopup/OptionButtons.test.tsx
  src/components/popup/PollPopup/OptionButtons.tsx
  src/components/popup/PollPopup/PollHeader.test.tsx
  src/components/popup/PollPopup/PollHeader.tsx
  src/components/popup/PollPopup/Question.test.tsx
  src/components/popup/PollPopup/Question.tsx
  src/components/popup/PollPopup/index.test.tsx
  src/components/popup/PollPopup/index.tsx
  src/components/provider/ReactQueryProvider.tsx
  src/exceptions/ApiErrorScheme.ts
  src/exceptions/ApiException.ts
  src/exceptions/CustomException.ts
  src/exceptions/errorMessage.ts
  src/lib/client.ts
  src/lib/queryClient.ts
  src/utils/testHelper.tsx
  yarn.lock
Labels: chore

#31 [POLL-004] recoil setting
  .pnp.cjs
  .yarn/cache/hamt_plus-npm-1.0.2-67a52ee1df-af26ea32db.zip
  .yarn/cache/recoil-npm-0.7.7-4452f58b67-65edecbcb8.zip
  README.md
  package.json
  src/app/(main)/layout.tsx
  src/app/(main)/page.tsx
  src/app/LayoutProvider.tsx
  src/components/home/PoPoImage.test.tsx
  src/components/home/PoPoImage.tsx
  src/components/home/PoPoTitle.test.tsx
  src/components/home/PoPoTitle.tsx
  src/components/home/VoteButton.test.tsx
  src/components/home/VoteButton.tsx
  src/components/home/index.test.tsx
  src/components/home/index.tsx
  src/components/layout/BottomNavigation.test.tsx
  src/components/layout/BottomNavigation.tsx
  src/components/layout/MainLayout.tsx
  src/components/layout/MobileLayout.tsx
  src/components/layout/NavigationItem.test.tsx
  src/components/layout/NavigationItem.tsx
  src/components/popup/FullPopup.test.tsx
  src/components/popup/PollPopup/CandidateItem.test.tsx
  src/components/popup/PollPopup/CandidateList.test.tsx
  src/components/popup/PollPopup/OptionButton.test.tsx
  src/components/popup/PollPopup/OptionButtons.test.tsx
  src/components/popup/PollPopup/PollHeader.test.tsx
  src/components/popup/PollPopup/Question.test.tsx
  src/components/provider/ReactQueryProvider.tsx
  src/hooks/recoil/usePoPoState.test.tsx
  src/hooks/recoil/usePoPoState.ts
  src/hooks/usePoPoText.test.tsx
  src/hooks/usePoPoText.ts
  src/lib/api/client.ts
  src/lib/api/exceptions/ApiErrorScheme.ts
  src/lib/api/exceptions/ApiException.ts
  src/lib/api/exceptions/CustomException.ts
  src/lib/api/exceptions/errorMessage.ts
  src/lib/api/queryClient.ts
  src/lib/assets/freind-icon.svg
  src/lib/assets/my-icon.svg
  src/lib/assets/popo-icon.svg
  src/lib/assets/who-icon.svg
  src/store/popo/index.ts
  src/test/MockProvider.tsx
  src/test/ReactQueryWrapper.tsx
  src/test/RecoilObserver.tsx
  src/utils/testHelper.tsx
  yarn.lock
Labels: feature

#34 [COMMONUI] 공통 컴포넌트 작업
  src/components/common/Button.tsx
  src/components/common/SmallButton.tsx
  src/components/home/VoteButton.tsx
  src/components/layout/MobileLayout.tsx
  src/styles/basicColors.ts
  src/styles/darkTheme.ts
  src/styles/defaultTheme.ts
Labels: feature

#39 [Login_Forget] 비밀번호 찾기 페이지 UI를 개발하라.
  src/app/(non-member)/find-password/page.tsx
  src/components/common/Button.tsx
  src/components/common/TextField.tsx
  src/components/find-password/FindPasswordForm.test.tsx
  src/components/find-password/FindPasswordForm.tsx
  src/components/find-password/StepButton.test.tsx
  src/components/find-password/StepButton.tsx
  src/components/find-password/StepTitle.test.tsx
  src/components/find-password/StepTitle.tsx
  src/components/find-password/index.test.tsx
  src/components/find-password/index.tsx
  src/components/home/PoPoImage.test.tsx
  src/components/home/VoteButton.test.tsx
  src/components/home/index.test.tsx
  src/components/layout/BottomNavigation.test.tsx
  src/components/layout/BottomNavigation.tsx
  src/components/layout/NavigationItem.tsx
  src/components/popup/PollPopup/index.test.tsx
  src/components/popup/Portal.test.tsx
  src/components/signin/LoginButtons.test.tsx
  src/components/signin/LoginButtons.tsx
  src/components/signin/LoginForm.test.tsx
  src/components/signin/LoginForm.tsx
  src/components/signin/index.test.tsx
  src/components/signin/index.tsx
  src/hooks/useFindPasswordForm.test.ts
  src/hooks/useFindPasswordForm.ts
  src/hooks/useSignInForm.ts
  src/hooks/useValidationPattern.ts
  src/styles/GlobalStyle.ts
  src/types/InputForm.ts
  src/types/Navigation.ts
  src/utils/sizeHelper.test.tsx
  src/utils/testHelper.tsx
Labels: feature

#43 [Modal] 공통으로 사용하는 Modal을 개발하라.
  src/app/layout.tsx
  src/components/find-password/index.test.tsx
  src/components/home/index.test.tsx
  src/components/home/index.tsx
  src/components/popup/FullPopup.test.tsx
  src/components/popup/FullPopup.tsx
  src/components/popup/NormalPopup.test.tsx
  src/components/popup/NormalPopup.tsx
  src/components/popup/PollPopup/PollHeader.test.tsx
  src/components/popup/PollPopup/PollHeader.tsx
  src/components/popup/PollPopup/PollPopDetail.test.tsx
  src/components/popup/PollPopup/PollPopDetail.tsx
  src/components/popup/PollPopup/index.tsx
  src/components/popup/PopupButtons.test.tsx
  src/components/popup/PopupButtons.tsx
  src/components/popup/Portal.test.tsx
  src/components/popup/Portal.tsx
  src/components/popup/SprintMotion.tsx
  src/components/signin/index.test.tsx
  src/hooks/useFindPasswordForm.test.ts
  src/hooks/useFindPasswordForm.ts
  src/hooks/useSignInForm.test.ts
  src/hooks/useSignInForm.ts
  src/styles/basicColors.ts
  src/utils/testHelper.tsx
Labels: feature

#26 [POLL-014] 힌트 알림 페이지를 개발하라.
  public/images/profile-female.svg
  public/images/profile-male.svg
  src/app/(main)/alarm/page.tsx
  src/components/alarm/AlarmItemBox.test.tsx
  src/components/alarm/AlarmItemBox.tsx
  src/components/alarm/HintBox.test.tsx
  src/components/alarm/HintBox.tsx
  src/components/alarm/index.test.tsx
  src/components/alarm/index.tsx
  src/components/common/ProfileIcon.tsx
  src/components/popup/NormalPopup.test.tsx
  src/fixtures/alarm.ts
  src/fixtures/hint.ts
  src/fixtures/index.ts
  src/styles/fontStyles.ts
  src/test/MockTheme.tsx
  src/test/RecoilObserver.tsx
  src/types/Alarm.ts
  src/types/Hint.ts
  src/types/User.ts
Labels: feature

#46 [CI] ChatGPT Review 삭제
  .github/workflows/cr.yml
Labels: ci/cd

#53 [SignUP] 회원가입 페이지 UI를 개발하라.
  public/images/female-icon.svg
  public/images/male-icon.svg
  src/app/(non-member)/signup/page.tsx
  src/app/layout.tsx
  src/components/common/TextField.test.tsx
  src/components/common/TextField.tsx
  src/components/find-password/FindPasswordForm.tsx
  src/components/find-password/StepTitle.tsx
  src/components/find-password/index.tsx
  src/components/signin/LoginForm.tsx
  src/components/signup/SignUpButton.test.tsx
  src/components/signup/SignUpButton.tsx
  src/components/signup/SignUpForm.test.tsx
  src/components/signup/SignUpForm.tsx
  src/components/signup/SignUpTitle.test.tsx
  src/components/signup/SignUpTitle.tsx
  src/components/signup/StepField/CertificationField.test.tsx
  src/components/signup/StepField/CertificationField.tsx
  src/components/signup/StepField/ConfirmField.test.tsx
  src/components/signup/StepField/ConfirmField.tsx
  src/components/signup/StepField/EmailField.test.tsx
  src/components/signup/StepField/EmailField.tsx
  src/components/signup/StepField/GenderSelector.test.tsx
  src/components/signup/StepField/GenderSelector.tsx
  src/components/signup/StepField/NameField.test.tsx
  src/components/signup/StepField/NameField.tsx
  src/components/signup/StepField/PasswordField.test.tsx
  src/components/signup/StepField/PasswordField.tsx
  src/components/signup/StepField/SchoolField.test.tsx
  src/components/signup/StepField/SchoolField.tsx
  src/components/signup/StepField/YearField.test.tsx
  src/components/signup/StepField/YearField.tsx
  src/components/signup/index.test.tsx
  src/components/signup/index.tsx
  src/fixtures/signupField.ts
  src/hooks/useFindPasswordForm.ts
  src/hooks/useGetDefaultRegister.ts
  src/hooks/usePoPoForm.ts
  src/hooks/useSignInForm.ts
  src/hooks/useSignUpForm.test.tsx
  src/hooks/useSignUpForm.ts
  src/hooks/useValidationPattern.ts
  src/types/Gender.ts
  src/types/InputForm.ts
  src/types/School.ts
Labels: feature

#54 [SignUp] 학교 검색 화면을 개발하라(팝업 형태)
  public/images/arrow-icon.svg
  public/images/black-school-icon.svg
  public/images/light-school-icon.svg
  src/components/common/SearchField.test.tsx
  src/components/common/SearchField.tsx
  src/components/common/TextField.tsx
  src/components/popup/SchoolPopup/SchoolItem.test.tsx
  src/components/popup/SchoolPopup/SchoolItem.tsx
  src/components/popup/SchoolPopup/SchoolPopDetail.test.tsx
  src/components/popup/SchoolPopup/SchoolPopDetail.tsx
  src/components/popup/SchoolPopup/index.tsx
  src/components/signup/StepField/ConfirmField.test.tsx
  src/components/signup/StepField/SchoolField.test.tsx
  src/components/signup/StepField/SchoolField.tsx
  src/fixtures/index.ts
  src/fixtures/school.ts
  src/fixtures/signupField.ts
  src/hooks/useSignUpForm.test.tsx
  src/hooks/useSignUpForm.ts
  src/lib/assets/search-icon.svg
  src/types/School.ts
Labels: feature

#58 [BUG] middleware matcher로 이미지 출력 안되는 문제해결
  src/middleware.ts
Labels: bugfix
